blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/2YzakxfyaC
    about: Join the community chat.
  - name: Telegram
    url: https://t.me/open_fnzero
    about: Join the Telegram group.
